name: DonatorUI
version: 3.4
main: Hytlenz\DonatorUI
api: [3.0.0, 4.0.0]
author: Hytlenz
description: Special Forms for Donators in your Server

commands:
  donator:
    description: "Donator form commands"
    permission: donator.ui
