---
#DonatorUI Config
#By Hytlenz
#Credits to Codeeeh to fix Errors
#Property of PCP Plugins
 
#Donator UI Message
donator:
 title: "§lDonator Form"
 content: "§fDonator Commands List. \n§bPlugin By: Hytlenz"

#Cure Message
cure.msg: "§l§8(§b!§8) §r§aYou have been §bCured!"
#Cleansing Effect Message
effect.msg: "§l§8(§b!§8) §r§aCleared all effects!"

#Fly Message
fly:
 title: "§lFly Form"
 content: "§fFlyUI Access Platform"
 on: "§l§8(§b!§8) §r§aFlight Enabled!"
 off: "§l§8(§b!§8) §r§cFlight Disabled!"

#Vanish Message
vanish:
 title: "§lVanish Form"
 content: "§fVanishUI Access Platform"
 on: "§l§8(§b!§8) §r§aYou are now Vanished!"
 off: "§l§8(§b!§8) §r§aYou are now Visible!"
 
#Nickname Message
nickmain:
 title: "§lNick Main Form"
 content: "§fChoose whether to edit or reset"
nick:
 title: "§lNickname Form"
 msg: "§l§8(§b!§8) §r§aYou succesfully update your nick!"
 reset: "§l§8(§b!§8) §r§aYou succesfully clear your nick"
 label: "§fJust set your nickname"

#Gamemode Message
gm:
 title: "§lGamemode Form"
 content: "§fGamemodeUI Access Platform"
 gms: "§l§8(§b!§8) §r§aYou're on gamemode §bSurvival!"
 gmc: "§l§8(§b!§8) §r§aYou're on gamemode §bCreative!"
 gmsp: "§l§8(§b!§8) §r§aYou're on gamemode §bSpectator!"

#Lights Message
lights:
 title: "§lLights Form"
 content: "§fLightsUI Access Platform"
 on: "§l§8(§b!§8) §r§aLights On!"
 off: "§l§8(§b!§8) §r§cLights Off!"

#Crawl Message
crawl:
 title: "§lCrawl Form"
 content: "§fCrawlUI Access Platform"
 on: "§l§8(§b!§8) §r§aCrawl On!"
 off: "§l§8(§b!§8) §r§cCrawl Off!"

#Time Set Message
time:
 title: "§lTime Set Form"
 content: "§fTime Set Access Platform"
 day: "§l§8(§b!§8) §r§aTime Set Day!"
 night: "§l§8(§b!§8) §r§aTime Set Night!"
 
#Size Message
size:
 title: "§lSize Form"
 content: "§fSizeUI Access Platform"
 baby: "§l§8(§b!§8) §r§aYour Size is Baby!"
 kid: "§l§8(§b!§8) §r§aYour Size is Kid!"
 teen: "§l§8(§b!§8) §r§aYour Size is Teen!"
 default: "§l§8(§b!§8) §r§aYour Size is Default!"
 giant: "§l§8(§b!§8) §r§aYour Size is Giant!"
...
