---
#DonatorUI Config
#By Hytlenz
#Credits to Codeeeh to fix Errors
#Property of PCP Plugins
#For img-type: 0 [ for resource packs images from MCPE ]
#              1 [ from the internet ]

# When a Player dont have Permission
error:
 title: "§l§cError"
 subtitle: "§4You Dont Have Permission"

# Main Form of Donator
donator:
 title: "§lDonator Form"
 content: "§fDonator Commands List. \n§bPlugin By: Hytlenz"

#Cure Message
cure:
 btn: "§lCure\n§rTap To Heal and Feed"
 img-type: 1
 img-url: "https://cdn2.iconfinder.com/data/icons/retro-game-items-revamp-border/100/heart_life_health_red_half-512.png"
 msg: "§l§8(§b!§8) §r§aYou have been §bCured!"
 
#Cleansing Effect Message
effect:
 btn: "§lCleanse\n§rTap To Clear Effects"
 img-type: 0
 img-url: "textures/ui/resistance_effect"
 msg: "§l§8(§b!§8) §r§aCleared all effects!"

#Fly Message
fly:
 btn: "§lFly\n§rTap To Glide"
 img-type: 1
 img-url: "http://icons.iconarchive.com/icons/ph03nyx/super-mario/256/Retro-P-Wing-icon.png"
 title: "§lFly Form"
 content: "§fFlyUI Access Platform"
 on: "§l§8(§b!§8) §r§aFlight Enabled!"
 off: "§l§8(§b!§8) §r§cFlight Disabled!"

#Vanish Message
vanish:
 btn:
 img-type:
 img-url:
 title: "§lVanish Form"
 content: "§fVanishUI Access Platform"
 on: "§l§8(§b!§8) §r§aYou are now Vanished!"
 off: "§l§8(§b!§8) §r§aYou are now Visible!"
 
#Nickname Message
nickmain:
 title: "§lNick Main Form"
 content: "§fChoose whether to edit or reset"
nick:
 btn:
 img-type:
 img-url:
 title: "§lNickname Form"
 msg: "§l§8(§b!§8) §r§aYou succesfully update your nick!"
 reset: "§l§8(§b!§8) §r§aYou succesfully clear your nick"
 label: "§fJust set your nickname"

#Gamemode Message
gm:
 btn:
 img-type:
 img-url:
 title: "§lGamemode Form"
 content: "§fGamemodeUI Access Platform"
 gms: "§l§8(§b!§8) §r§aYou're on gamemode §bSurvival!"
 gmc: "§l§8(§b!§8) §r§aYou're on gamemode §bCreative!"
 gmsp: "§l§8(§b!§8) §r§aYou're on gamemode §bSpectator!"

#Lights Message
lights:
 btn:
 img-type:
 img-url:
 title: "§lLights Form"
 content: "§fLightsUI Access Platform"
 on: "§l§8(§b!§8) §r§aLights On!"
 off: "§l§8(§b!§8) §r§cLights Off!"

#Crawl Message
crawl:
 btn:
 img-type:
 img-url:
 title: "§lCrawl Form"
 content: "§fCrawlUI Access Platform"
 on: "§l§8(§b!§8) §r§aCrawl On!"
 off: "§l§8(§b!§8) §r§cCrawl Off!"

#Time Set Message
time:
 btn:
 img-type:
 img-url:
 title: "§lTime Set Form"
 content: "§fTime Set Access Platform"
 day: "§l§8(§b!§8) §r§aTime Set Day!"
 night: "§l§8(§b!§8) §r§aTime Set Night!"
 
#Size Message
size:
 btn:
 img-type:
 img-url:
 title: "§lSize Form"
 content: "§fSizeUI Access Platform"
 baby: "§l§8(§b!§8) §r§aYour Size is Baby!"
 kid: "§l§8(§b!§8) §r§aYour Size is Kid!"
 teen: "§l§8(§b!§8) §r§aYour Size is Teen!"
 default: "§l§8(§b!§8) §r§aYour Size is Default!"
 giant: "§l§8(§b!§8) §r§aYour Size is Giant!"
...
